Name = c("Amiya", "Raj", "Asish", "Deven", "Sush")
Language = c("R", "Python", "Java","Python", "Python")
Age = c(22, 25, 45,24,24)
df = data.frame(Name, Language, Age)
print("Original Dataframe :")
print(df)
df <- df[-c(4,5),]
print("Dataframe After Deleting rows :")
print(df)
df = subset(df, select = -c(Age))
print("Dataframe After Deleting columns :")
print(df)
Name = c("Deven", "Sush")
Language = c("Python","Python")
new_df= data.frame(Name, Language)
df = rbind(df,new_df)
print("Dataframe After adding rows :")
print(df)
df$Age = c(21,25,23,24,24)
print("Dataframe After adding columns :")
print(df)